instance_config = {
  "rs_base_url":"https://foo.bar",
  "username":"it_me",
  "api_key":"123abc",
  "mappings":{
    "art":{
      "RESOURCE_TYPE":1,
      "UMO ID":999,
      "CATEGORIES":999,
      "FILE NAME":51,
      "TAGS":91,
      "ARTISTFILMMAKER":86,
      "TITLE":8,
      "YEAR":121,
      "ARTISTORIGIN":122,
      "COPYRIGHTCREDIT":10,
      "DESCRIPTION":88,
      "FULLBAMPFACREDITLINE":96,
      "IDNUMBER":104,
      "ITEMCLASS":106,
      "MATERIALS":107,
      "MEASUREMENT":108,
      "OBJECTCSID":116,
      "PERIODSTYLES":109,
      "PHOTOCREDIT":93,
      "SUBJECTS":89,
      "SOURCE":54,
      "ARTISTDATES":110,
      "ARTISTORIGIN":105,
      "COLLECTIONS":124,
      "SITE":129,
      "IMAGE RIGHTS":130
    },
    "film":{
      "RESOURCE_TYPE":6,
      "UMO ID":999,
      "FILE NAME":51,
      "CATEGORIES":999,
      "TAGS":91,
      "ARTISTFILMMAKER":86,
      "TITLE":8,
      "YEAR":121,
      "DC-DESCRIPTION":88,
      "DC-CONTRIBUTOR":54,
      "DC-RIGHTS":10,
      "DC-SUBJECT":90,
      "DC-TYPE":97,
      "UPDATEDAT":12,
      "CINEFILES-ID":101,
      "DC-PUBLISHER":100
    },
    "exhibitions":{
      "RESOURCE_TYPE":2,
      "UMO ID":999,
      "FILE NAME":51,
      "CATEGORIES":999,
      "TAGS":91,
      "ARTISTFILMMAKER":86,
      "TITLE":8,
      "YEAR":121,
      "FULL_EXHIBIT_DATE":112,
      "BAM_PFA_CAPTION":18,
      "DC-DESCRIPTION":88,
      "ARTWORK_MEDIUM":113,
      "CURATOR":114,
      "EXHIBITION LOCATION":92,
      "DC-CONTRIBUTOR":54,
      "PHOTO_CREDIT":93,
      "ARTWORK_CREDIT_LINE":96,
      "COPYRIGHT":10,
      "DC-TYPE":97,
      "DC-TITLE":128,
      "RESTRICTIONS":94
    },
    "events":{
      "RESOURCE_TYPE":6,
      "UMO ID":999,
      "FILENAME":51,
      "CATEGORIES":999,
      "TITLE":8,
      "YEAR":121,
      "DC-COVERAGE":92,
      "DC-PUBLISHER":100,
      "RELATED_EXHIBITIONS":98,
      "EVENT_LOCATION":92,
      "DC-DESCRIPTION":88,
      "DC-COVERAGE":131,
      "DC-TYPE":97,
      "DC-SUBJECT":90,
      "TOPICAL_SUBJECT":89,
      "ORGANIZER":132,
      "DC-CONTRIBUTOR":54,
      "TAGS":91,
      "DC-AUTHOR":93,
      "BAM_PFA_CAPTION":18,
      "RESTRICTIONS":94
    },
    "institutional":{
      "RESOURCE_TYPE":6,
      "UMO ID":999,
      "CATEGORIES":999,
      "FILE NAME":51,
      "CATEGORIES":999,
      "YEAR":121,
      "TAGS":91,
      "DC-DESCRIPTION":88,
      "DC-SUBJECT":89,
      "TITLE":8,
      "DC-AUTHOR":93,
      "DC-RIGHTS":10,
      "LOCATION_PICTURED":92
    }
  }
}
